name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          .cpcache
          .shadow-cljs
          node_modules
          ~/.m2/repository
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn', '**/package-lock.json') }}

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.469'      

    - name: Compile
      run: |
        npm install &&
        clojure -A:shadow-cljs release app

    - name: Deploy Demo Pages
      uses: JamesIves/github-pages-deploy-action@3.5.8
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: resources/public

    - name: Upload Demo Artifact
      uses: actions/upload-artifact@v2
      with:
        name: demo
        path: resources/public/


