name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          .cpcache
          .shadow-cljs
          node_modules
          ~/.m2/repository
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn', '**/package-lock.json') }}

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.0
      with:
        tools-deps: '1.10.1.469'

    - name: Prepare
      run: npm install

    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2023.02.17'

    - name: Lint
      run: clj-kondo --lint src --config .github/clj-kondo.edn

    - name: Test
      run: |
        clojure -M:client release ci
        ./node_modules/karma/bin/karma start --single-run || true

    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_paths: '**/karma/results/TESTS-*.xml'

    - name: Compile
      run: clojure -M:shadow-cljs:client release app

    - name: Prepare Site
      run: |
        mkdir -p site/demo
        cp README.md site/README.md
        cp -R resources/public/* site/demo/

    - name: Deploy Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: site

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: demo
        path: resources/public/
